# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/paths/cm_consentRequests.yaml:
  operation-4xx-response:
    - '#/post/responses'
