openapi: 3.1.0
info:
  version: 0.9.1
  title: AgriStack Consent Management (ACM) APIs
    # termsOfService: https://example.com/terms/
  contact:
    email: saurabh.panjwani [AT-the-RATE-of] gmail.com
      # url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    # See Vendor extensions: https://github.com/Redocly/Redoc/blob/main/docs/redoc-vendor-extensions.md#x-summary
    url: https://saurabhpanjwani.github.io/images/agristack-logo.png  
  description: >
    This is the set of all AgriStack Consent Management (ACM) APIs written using OpenAPI
    specification.

    # Introduction
    
    There are four categories of APIs in the ACM Framework-- **network manager (NM)** APIs, 
    **AIP** APIs, **CM** APIs, and **AIU** APIs. Each of these categories is 
    listed in the left panel and the individual APIs are described below.

    # OpenAPI Specification

    The goal of The OpenAPI Specification is to define a standard, language-agnostic 
    interface to REST APIs which allows both humans and computers to discover and 
    understand capabilities of services without access to source code or documentation. 
    Similar to what interfaces have done for lower-level programming, OpenAPI removes 
    the guesswork in calling services.
tags:
  - name: NM
    description: network manager (NM) APIs
  - name: AIP
    description: agri information provider (AIP) APIs
  - name: CM
    description: consent manager (CM) APIs
  - name: AIU
    description: agri information user (AIU) APIs
servers:
  - url: https://{tenant}/api
    description: Server where the API is hosted
    variables:
      tenant:
        default: www
        description: Tenant ID 
paths:
  /nm/serviceInfo:
    $ref: paths/nm_serviceInfo.yaml
  /cm/consentRequests:
    $ref: paths/cm_consentRequests.yaml
  /cm/consentArtifacts/{artifactId}:
    $ref: paths/cm_consentArtifacts_{artifactId}.yaml
  /aiu/consentRequestAcks:
    $ref: paths/aiu_consentRequestAcks.yaml
  /aiu/consentStatus/{artifactId}:
    $ref: paths/aiu_consentStatus_{artifactId}.yaml
      # /aip/consentNotifications/{artifactId}:
      # $ref: paths/aip_consentNotifications_{artifactId}.yaml
  /aip/dataRequests:
    $ref: paths/aip_dataRequests.yaml
  /aip/data/{artifactId}:
    $ref: paths/aip_data_{artifactId}.yaml
components:
  securitySchemes:
    #main_auth:
    #  type: oauth2
    #  flows:
    #    implicit:
    #      authorizationUrl: http://example.com/api/oauth/dialog
    #      scopes:
    #        read:users: read users info
    #        write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
